- name: "Remove terminal configuration for Ly in '{{ lightdm_freebsd_terminal_config_path }}'"
  ansible.builtin.blockinfile:
    path: "{{ lightdm_freebsd_terminal_config_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Ly display manager terminal config"
    state: absent
    create: false
  become: true
  become_user: root

- name: "Restore default virtual console {{ lightdm_freebsd_ly_virtual_console_num }} config in '{{ lightdm_freebsd_console_config_path }}'"
  ansible.builtin.lineinfile:
    path: "{{ lightdm_freebsd_console_config_path }}"
    regexp: >-
      ^(# )?ttyv{{ lightdm_freebsd_ly_virtual_console_num }}(.*)$
    line: >-
      ttyv{{ lightdm_freebsd_ly_virtual_console_num }}\2
    state: present
    firstmatch: true
    create: false
    backrefs: true
    backup: true
  become: true
  become_user: root

- name: "Remove virtual console {{ lightdm_freebsd_ly_virtual_console_num }} config for Ly in '{{ lightdm_freebsd_console_config_path }}'"
  ansible.builtin.blockinfile:
    path: "{{ lightdm_freebsd_console_config_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Ly virtual console config"
    state: absent
    create: false
  become: true
  become_user: root

